name = "bona-erp-api"
main = "src/worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "0fbce6165150f90e7f385e373182204e"

# 环境变量
[vars]
NODE_ENV = "production"
JWT_SECRET = "bona-erp-prod-jwt-secret-2026"

# D1 数据库（SQLite 兼容，Prisma D1 Adapter）
[[d1_databases]]
binding = "DB"
database_name = "bona-erp-db"
database_id = ""

# 环境特定配置
[env.production]
name = "bona-erp-api-production"
